### ISSUE TITLE
Revert to latest MongoDB version when the supercharged github action gets fixed

### ISSUE THREAD

**Issue by tmasternak** [Particular/setup-mongodb-action#3]
Once the community action for setting up the MongoDB is [fixed](https://github.com/supercharge/mongodb-github-action/issues/34) we can revert back to using `latest` as the MongoDB version.

//cc: @danielmarbach

**Comment by danielmarbach** [comment]
We decided to stay with 5.x because that is aligned with the version that is installed on the Windows Images.
